name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build production bundle
        run: npm run build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Distribution
          path: dist

      - name: Create dist.zip
        uses: thedoctor0/zip-release@master
        with:
          filename: dist.zip
          path: dist
      
      - name: Automatic release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger web hook for publish workflow
        if: steps.semantic.outputs.new_release_published == 'true' && env.GITHUB_TOKEN != 0
        uses: octokit/request-action@v2.x
        id: create_repository_dispatch
        with:
          route: POST /repos/:repository/dispatches
          repository: ${{ github.repository }}
          event_type: v${{ steps.semantic.outputs.new_release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
